### ISSUE TITLE
NPM Install Problems

### ISSUE THREAD

**Issue by Mtechnik** [dscalzi/ElectronLauncher#30]
`npm ERR! sodium@3.0.2 preinstall: `node install.js --preinstall`` is the NPM as it states in your @readme.md page once the files are downloaded. then run `npm install`.

Here is my Logfile.
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'sodium',
1 verbose cli   '--preinstall',
1 verbose cli   '-g' ]
2 info using npm@6.7.0
3 info using node@v11.10.1
4 verbose npm-session 054a677b78577ab6
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/sodium 30ms (from cache)
8 silly pacote tag manifest for sodium@latest fetched in 68ms
9 timing stage:loadCurrentTree Completed in 117ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule sodium@3.0.2 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/node-addon-api 13ms (from cache)
18 silly pacote range manifest for node-addon-api@* fetched in 16ms
19 silly resolveWithNewModule node-addon-api@1.6.2 checking installable status
20 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 26ms
21 timing stage:loadIdealTree Completed in 29ms
22 silly currentTree npm
23 silly idealTree npm
23 silly idealTree `-- sodium@3.0.2
23 silly idealTree   `-- node-addon-api@1.6.2
24 silly install generateActionsToTake
25 timing stage:generateActionsToTake Completed in 6ms
26 silly diffTrees action count 2
27 silly diffTrees add node-addon-api@1.6.2
28 silly diffTrees add sodium@3.0.2
29 silly decomposeActions action count 16
30 silly decomposeActions fetch node-addon-api@1.6.2
31 silly decomposeActions extract node-addon-api@1.6.2
32 silly decomposeActions preinstall node-addon-api@1.6.2
33 silly decomposeActions build node-addon-api@1.6.2
34 silly decomposeActions install node-addon-api@1.6.2
35 silly decomposeActions postinstall node-addon-api@1.6.2
36 silly decomposeActions finalize node-addon-api@1.6.2
37 silly decomposeActions refresh-package-json node-addon-api@1.6.2
38 silly decomposeActions fetch sodium@3.0.2
39 silly decomposeActions extract sodium@3.0.2
40 silly decomposeActions preinstall sodium@3.0.2
41 silly decomposeActions build sodium@3.0.2
42 silly decomposeActions install sodium@3.0.2
43 silly decomposeActions postinstall sodium@3.0.2
44 silly decomposeActions finalize sodium@3.0.2
45 silly decomposeActions refresh-package-json sodium@3.0.2
46 silly install executeActions
47 silly doSerial global-install 16
48 verbose correctMkdir C:\Users\nanob\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
49 verbose lock using C:\Users\nanob\AppData\Roaming\npm-cache\_locks\staging-c4c8c3742a8746b1.lock for C:\Users\nanob\AppData\Roaming\npm\node_modules\.staging
50 silly doParallel extract 2
51 silly extract node-addon-api@1.6.2
52 silly extract sodium@3.0.2
53 silly tarball trying node-addon-api@* by hash: sha512-479Bjw9nTE5DdBSZZWprFryHGjUaQC31y1wHo19We/k0BZlrmhqQitWoUL0cD8+scljCbIUL+E58oRDEakdGGA==
54 silly tarball trying sodium@latest by hash: sha512-IsTwTJeoNBU97km3XkrbCGC/n/9aUQejgD3QPr2YY2gtbSPru3TI6nhCqgoez9Mv88frF9oVZS/jrXFbd6WXyA==
55 silly extract node-addon-api@* extracted to C:\Users\nanob\AppData\Roaming\npm\node_modules\.staging\node-addon-api-808edf68 (145ms)
56 silly extract sodium@latest extracted to C:\Users\nanob\AppData\Roaming\npm\node_modules\.staging\sodium-9c2c6e16 (892ms)
57 timing action:extract Completed in 897ms
58 silly doReverseSerial unbuild 16
59 silly doSerial remove 16
60 silly doSerial move 16
61 silly doSerial finalize 16
62 silly finalize C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium\node_modules\node-addon-api
63 silly finalize C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium
64 timing action:finalize Completed in 15ms
65 silly doParallel refresh-package-json 2
66 silly refresh-package-json C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium\node_modules\node-addon-api
67 silly refresh-package-json C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium
68 timing action:refresh-package-json Completed in 293ms
69 silly doParallel preinstall 2
70 silly preinstall node-addon-api@1.6.2
71 info lifecycle node-addon-api@1.6.2~preinstall: node-addon-api@1.6.2
72 silly preinstall sodium@3.0.2
73 info lifecycle sodium@3.0.2~preinstall: sodium@3.0.2
74 verbose lifecycle sodium@3.0.2~preinstall: unsafe-perm in lifecycle true
75 verbose lifecycle sodium@3.0.2~preinstall: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium\node_modules\.bin;C:\Users\nanob\AppData\Roaming\npm\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY\;C:\Users\nanob\AppData\Local\Microsoft\WindowsApps;;D:\Programs\Microsoft VS Code\bin;C:\Users\nanob\AppData\Roaming\npm;C:\Program Files\JetBrains\WebStorm 2018.3.5\bin;
76 verbose lifecycle sodium@3.0.2~preinstall: CWD: C:\Users\nanob\AppData\Roaming\npm\node_modules\sodium
77 silly lifecycle sodium@3.0.2~preinstall: Args: [ '/d /s /c', 'node install.js --preinstall' ]
78 silly lifecycle sodium@3.0.2~preinstall: Returned: code: 1  signal: null
79 info lifecycle sodium@3.0.2~preinstall: Failed to exec preinstall script
80 timing action:preinstall Completed in 195ms
81 verbose unlock done using C:\Users\nanob\AppData\Roaming\npm-cache\_locks\staging-c4c8c3742a8746b1.lock for C:\Users\nanob\AppData\Roaming\npm\node_modules\.staging
82 timing stage:rollbackFailedOptional Completed in 358ms
83 timing stage:runTopLevelLifecycles Completed in 1923ms
84 verbose stack Error: sodium@3.0.2 preinstall: `node install.js --preinstall`
84 verbose stack Exit status 1
84 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
84 verbose stack     at EventEmitter.emit (events.js:197:13)
84 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
84 verbose stack     at ChildProcess.emit (events.js:197:13)
84 verbose stack     at maybeClose (internal/child_process.js:984:16)
84 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
85 verbose pkgid sodium@3.0.2
86 verbose cwd E:\ElectronLauncher-1.6.0
87 verbose Windows_NT 10.0.17134
88 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "sodium" "--preinstall" "-g"
89 verbose node v11.10.1
90 verbose npm  v6.7.0
91 error code ELIFECYCLE
92 error errno 1
93 error sodium@3.0.2 preinstall: `node install.js --preinstall`
93 error Exit status 1
94 error Failed at the sodium@3.0.2 preinstall script.
94 error This is probably not a problem with npm. There is likely additional logging output above.
95 verbose exit [ 1, true ]
`

**Comment by dscalzi** [comment]
I'm not getting this issue. Try deleting node_modules and running the command again.
