### ISSUE TITLE
Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by AzureZhen** [dscalzi/ElectronLauncher#34]
Issue: Invalid or unsupported zip format. No END header found
https://gist.github.com/AzureZhen/b9a72325e862212010063e84611417a7

This is a random bug that randomly affects some users, not sure what causes this bug at all.

This is my distribution file: http://cc2web.cyberconnects2.com/games/rcraft/distribution.json

**Comment by dscalzi** [comment]
I don't know why this would happen. The only reason I can think of is that the file did not finish downloading when the zip extraction started. That shouldnt be able to happen, though. The launch process only proceeds when all data is received for the downloaded files.

Ask one of your users to send you a copy of the forge jar that was downloaded by the launcher (your Forge-Hosted module). If there's no content, it may be that their antivirus is flagging your hosting site and not letting the download through.

**Comment by AzureZhen** [comment]
Good suggestion, the host has had issues in the past. I'll throw it up on a spare webhost I use for testing and see if they still have the issue. Will update this comment with results.

**Comment by AzureZhen** [comment]
Alright changing my ForgeHosted to http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2836/forge-1.12.2-14.23.5.2836-universal.jar fixed the Invalid or unsupported zip format. No END header found issue it seems. Now I need to it being stuck on 100%.

**Comment by AzureZhen** [comment]
Alright I see the 100% looks to be the issue with #24 closing this issue for now.
