### ISSUE TITLE
Own yggdrasil auth 

### ISSUE THREAD

**Issue by DarkScientist** [dscalzi/ElectronLauncher#35]
Hi,
Is there any way to set my custom yggdrasil's auth server? And can I use the launcher for my own usage?

**Comment by dscalzi** [comment]
1. You can change the authentication code to whatever suits your needs. Just don't have users input their Mojang credentials through your server. That must be sent directly to Mojang's authentication service. If you manage your own credentials and they are separate from Mojang's, then you're fine. See the Mojang API wrapper (https://github.com/dscalzi/ElectronLauncher/blob/master/app/assets/js/mojang.js) and AuthManager (https://github.com/dscalzi/ElectronLauncher/blob/master/app/assets/js/authmanager.js) for details.
2. You can use the launcher as long as you follow the brief terms of use. https://github.com/dscalzi/ElectronLauncher#note-on-third-party-usage
