### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by DarkScientist** [dscalzi/ElectronLauncher#37]
Hi,

I got this error while trying to build the launcher for Linux.
Building for windows works perfectly...

Here are the logs :
[pastebin](https://pastebin.com/kMwM4wT6)

Thanks for your response !!

**Comment by AndrusGerman** [comment]
Can you be a little more detailed with your system?
It currently works perfectly with the following features:

**Comment by AndrusGerman** [comment]
Can you be a little more detailed with your system?
It currently works perfectly with the following features:

**Comment by AndrusGerman** [comment]
[andrusd@andrusd-pc ElectronLauncher]$ npm --version
6.10.2
[andrusd@andrusd-pc ElectronLauncher]$ node --version
v11.15.0

**Comment by DarkScientist** [comment]
Hi,
Thanks for you response! 
However, I can build a launcher where I haven't modified any icon from the build folder... 
And the error looks like about it... 

I'm using windows 10 and the last npm version. 

Is there any restriction about the icon?

**Comment by AzureZhen** [comment]
This was an issue with the icon background. Seemed to be a color the builder didn't like for Linux. Made it transparent and that fixed the issue.

**Comment by AzureZhen** [comment]
Might be a good idea to close this issue @DarkScientist
