### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by pepyta** [dscalzi/ElectronLauncher#8]
Without a License we are not permitted to modify or help in the developement in the code.
If this is a mistake please add a License file for it!

**Comment by Eddi2015** [comment]
Little bump here. I am working on a fork of this repo and I'd like to know the license. I propose LGPL v3

**Comment by dscalzi** [comment]
All rights reserved for now.

https://github.com/WesterosCraftCode/ElectronLauncher#note-on-third-party-usage
